n_layers: 2
n_heads: 2
hidden_size: 128
inner_size: 128
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
hidden_act: 'gelu'
layer_norm_eps: 1e-12
initializer_range: 0.02
loss_type: 'CE'
init_range: 0.5